global:
  scrape_interval:      15s
  evaluation_interval:  15s

scrape_configs:
  - job_name: 'tsmok_metrics'
    static_configs:
      - targets: ['statsd_exporter_tsmok:9102']
  - job_name: 'dta_metrics'
    static_configs:
      - targets: ['statsd_exporter_dta:9102']
